global:
  resolve_timeout: 5m

route:
  receiver: opsgenie
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: opsgenie
    opsgenie_configs:
      - api_key: "<seu_token_de_api>" # Substitua pela sua chave de API OpsGenie
