groups:
  - name: test-alerts
    rules:
      - alert: TestAlert
        expr: vector(1) == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Test Alert"
          description: "This is a test alert to verify OpsGenie integration."
